algo: PPO
policy: MlpPolicy
learning_rate: 0.0001
learning_rate_schedule: linear
gamma: 0.99
gae_lambda: 0.95
n_steps: 4096
batch_size: 1024
n_epochs: 10
ent_coef: 0.01
clip_range: 0.2
target_kl: 0.02
policy_kwargs:
  net_arch: [256, 256]
total_timesteps: 5000000
seed: 42
env:
  max_queue: 20
  lambda_ns: 0.5
  lambda_ew: 0.5
  veh_throughput: 3
  min_green: 10
  yellow: 3
  episode_len: 1500
  decision_interval: 1
  # Reward shaping
  wait_w: 1.0
  max_w: 0.1
  switch_w: 0.5
  served_w: 0.08
  imbalance_w: 0.05
  hold_w: 0.02
# Domain randomization is disabled by default; uncomment to re-enable.
# rand:
#   lambda_scale_min: 0.7
#   lambda_scale_max: 1.3
